"""Spline basis + SplineMemoryPolynomial: math, fitting, integration."""

import numpy as np
import pytest

from padpd.pa import (MemoryPolynomialModel, ReferencePA, SplineGMP,
                      SplineMemoryPolynomial, bspline_design_matrix,
                      nmse_db, place_knots)
from padpd.waveform import OFDMConfig, generate_ofdm

BREAKPOINTS = [0.0, 0.1, 0.25, 0.4, 0.6, 1.0]


@pytest.fixture(scope="module")
def ofdm_signal():
    cfg = OFDMConfig(bandwidth_hz=80e6, qam_order=256, n_symbols=8, seed=11)
    return generate_ofdm(cfg).x


@pytest.fixture(scope="module")
def pa_data(ofdm_signal):
    pa = ReferencePA()
    return ofdm_signal, pa(ofdm_signal)


# ---- basis math -----------------------------------------------------

@pytest.mark.parametrize("degree", [1, 2, 3])
def test_design_matrix_matches_scipy(degree):
    from scipy.interpolate import BSpline
    rng = np.random.default_rng(0)
    r = rng.uniform(0.0, 1.0, 500)
    t = np.concatenate([np.full(degree, BREAKPOINTS[0]), BREAKPOINTS,
                        np.full(degree, BREAKPOINTS[-1])])
    ours = bspline_design_matrix(r, BREAKPOINTS, degree)
    ref = BSpline.design_matrix(r, t, degree).toarray()
    np.testing.assert_allclose(ours, ref, atol=1e-12)


@pytest.mark.parametrize("degree", [1, 2, 3])
def test_partition_of_unity_including_clamp(degree):
    rng = np.random.default_rng(1)
    r = rng.uniform(-0.5, 2.0, 400)          # includes out-of-domain
    b = bspline_design_matrix(r, BREAKPOINTS, degree)
    np.testing.assert_allclose(b.sum(axis=1), 1.0, atol=1e-12)
    # right endpoint exactly representable
    b_end = bspline_design_matrix(np.array([BREAKPOINTS[-1]]),
                                  BREAKPOINTS, degree)
    assert b_end.sum() == pytest.approx(1.0)


def test_place_knots_variants(ofdm_signal):
    amps = np.abs(ofdm_signal)
    for placement in ("uniform", "quantile", "hybrid"):
        ks = place_knots(amps, n_knots=8, placement=placement)
        assert len(ks) == 8
        assert all(b > a for a, b in zip(ks, ks[1:]))
        assert ks[0] == 0.0 and ks[-1] == pytest.approx(amps.max())
    # quantile knots hit the empirical quantiles
    ks = place_knots(amps, n_knots=6, placement="quantile")
    lv = np.linspace(0, 1, 6)[1:-1]
    np.testing.assert_allclose(ks[1:-1], np.quantile(amps, lv), rtol=1e-12)
    # hybrid: tail is uniform from the tail_start quantile to r_max
    ks = place_knots(amps, n_knots=8, placement="hybrid", tail_start=0.95)
    assert ks[-2] == pytest.approx(np.quantile(amps, 0.95))
    # knee replaces the nearest interior knot, count preserved
    ks = place_knots(amps, n_knots=8, knee=0.02)
    assert len(ks) == 8 and 0.02 in ks
    with pytest.raises(ValueError):
        place_knots(amps, n_knots=1)
    with pytest.raises(ValueError):
        place_knots(amps, n_knots=8, placement="magic")


# ---- SplineMemoryPolynomial -----------------------------------------

def test_smp_exact_recovery():
    """SMP fit on data generated by an SMP model recovers it near-exactly."""
    rng = np.random.default_rng(0)
    x = (rng.standard_normal(20_000) + 1j * rng.standard_normal(20_000))
    x /= np.sqrt(2) * 2
    truth = SplineMemoryPolynomial(n_knots=6, r_max=1.5, memory_depth=3)
    n = truth.n_coeffs
    truth.coeffs = (rng.standard_normal(n)
                    + 1j * rng.standard_normal(n)) * 0.1
    truth.coeffs[:truth.n_basis] += 1.0
    y = truth(x)
    fitted = SplineMemoryPolynomial(knots=truth.knots,
                                    memory_depth=3).fit(x, y)
    assert nmse_db(y, fitted(x)) < -100


def test_smp_fits_reference_pa(pa_data):
    x, y = pa_data
    smp = SplineMemoryPolynomial.from_signal(x, n_knots=8,
                                             memory_depth=4).fit(x, y)
    assert nmse_db(y, smp(x)) < -35


def test_smp_from_signal_generalizes(pa_data):
    x_train, y_train = pa_data
    cfg = OFDMConfig(bandwidth_hz=80e6, qam_order=256, n_symbols=8, seed=99)
    x_val = generate_ofdm(cfg).x
    y_val = ReferencePA()(x_val)
    smp = SplineMemoryPolynomial.from_signal(x_train, n_knots=8,
                                             memory_depth=4)
    smp.fit(x_train, y_train)
    assert nmse_db(y_val, smp(x_val)) < -35


def test_smp_passthrough_is_identity():
    rng = np.random.default_rng(2)
    x = (rng.standard_normal(2000) + 1j * rng.standard_normal(2000)) * 0.2
    m = SplineMemoryPolynomial(n_knots=6, r_max=1.0, memory_depth=3)
    m.coeffs = m.passthrough_coeffs()
    np.testing.assert_allclose(m(x), x, atol=1e-12)


def test_smp_clamped_extrapolation(pa_data):
    """Beyond the top knot the complex gain holds its endpoint value."""
    x, y = pa_data
    smp = SplineMemoryPolynomial.from_signal(x, n_knots=8, memory_depth=1,
                                             headroom=1.0).fit(x, y)
    r_max = smp.knots[-1]
    probe = np.array([r_max, 1.5 * r_max, 3.0 * r_max], dtype=complex)
    out = smp(probe)
    assert np.all(np.isfinite(out))
    gains = out / probe
    np.testing.assert_allclose(gains, gains[0], rtol=1e-9)


def test_smp_constructor_validates():
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(knots=[0.0, 0.5, 0.4])      # not ascending
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(knots=[0.3])                # too few
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(knots=[-0.1, 0.5])          # negative
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(degree=4)
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(degree=0)
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(memory_depth=0)
    with pytest.raises(ValueError):
        SplineMemoryPolynomial(n_knots=1)


def test_smp_n_coeffs_and_config_roundtrip():
    m = SplineMemoryPolynomial(n_knots=8, r_max=1.0, degree=3,
                               memory_depth=4)
    assert m.n_basis == 8 - 1 + 3
    assert m.n_coeffs == 4 * 10
    import ast
    cfg = ast.literal_eval(repr(m.get_config()))
    m2 = SplineMemoryPolynomial(**cfg)
    assert m2.get_config() == m.get_config()


def test_smp_unfitted_raises():
    with pytest.raises(RuntimeError):
        SplineMemoryPolynomial()(np.zeros(10, dtype=complex))


# ---- SplineGMP ------------------------------------------------------

def test_sgmp_exact_recovery():
    rng = np.random.default_rng(3)
    x = (rng.standard_normal(20_000) + 1j * rng.standard_normal(20_000))
    x /= np.sqrt(2) * 2
    truth = SplineGMP(n_knots=5, r_max=1.5, memory_depth=3,
                      lag_memory=2, lag_span=1, lead_memory=2, lead_span=1)
    n = truth.n_coeffs
    truth.coeffs = (rng.standard_normal(n)
                    + 1j * rng.standard_normal(n)) * 0.1
    truth.coeffs[:truth.n_basis] += 1.0
    y = truth(x)
    fitted = SplineGMP(knots=truth.knots, memory_depth=3, lag_memory=2,
                       lag_span=1, lead_memory=2, lead_span=1).fit(x, y)
    assert nmse_db(y, fitted(x)) < -100


def test_sgmp_beats_smp(pa_data):
    """Cross-envelope spline branches capture memory the aligned SMP
    cannot, mirroring GMP-beats-MP on the polynomial side."""
    x, y = pa_data
    smp = SplineMemoryPolynomial.from_signal(x, n_knots=8,
                                             memory_depth=4).fit(x, y)
    sgmp = SplineGMP.from_signal(x, n_knots=8, memory_depth=4).fit(x, y)
    assert nmse_db(y, sgmp(x)) <= nmse_db(y, smp(x))


def test_sgmp_well_conditioned(pa_data):
    """The dropped cross-branch column removes the partition-of-unity
    rank deficiency: the SplineGMP basis must be numerically sane."""
    from padpd.pa import basis_cond
    x, _ = pa_data
    sgmp = SplineGMP.from_signal(x[:8192], n_knots=8, memory_depth=4)
    assert basis_cond(sgmp, x) < 1e6


def test_sgmp_passthrough_and_counts():
    m = SplineGMP(n_knots=6, r_max=1.0, memory_depth=3, lag_memory=2,
                  lag_span=2, lead_memory=1, lead_span=1)
    assert m.n_branches == 3 + 4 + 1
    # cross branches drop one column each (identifiability)
    assert m.n_coeffs == m.n_basis * 3 + (m.n_basis - 1) * 5
    rng = np.random.default_rng(4)
    x = (rng.standard_normal(2000) + 1j * rng.standard_normal(2000)) * 0.2
    m.coeffs = m.passthrough_coeffs()
    np.testing.assert_allclose(m(x), x, atol=1e-12)


def test_sgmp_constructor_validates():
    with pytest.raises(ValueError):
        SplineGMP(lag_span=-1)
    with pytest.raises(ValueError):
        SplineGMP(memory_depth=0)
    with pytest.raises(ValueError):
        SplineGMP(knots=[0.0, 0.5, 0.2])


def test_smp_better_conditioned_than_polynomial(pa_data):
    """The design-motivation claim: spline columns are far less collinear
    than |x|^k powers at comparable coefficient count."""
    from padpd.pa import basis_cond
    x, _ = pa_data
    mp = MemoryPolynomialModel(order=7, memory_depth=4)
    smp = SplineMemoryPolynomial.from_signal(x[:8192], n_knots=5,
                                             memory_depth=4)
    assert basis_cond(smp, x) < basis_cond(mp, x) / 100


# ---- gain_curve / branch metadata -----------------------------------

def test_gain_curve_matches_direct_evaluation(pa_data):
    """On a constant-envelope probe, tap-0 gain_curve must equal the
    model's actual complex gain (memoryless case isolates tap 0)."""
    x, y = pa_data
    smp = SplineMemoryPolynomial.from_signal(x, n_knots=8,
                                             memory_depth=1).fit(x, y)
    r = np.array([0.02, 0.05, 0.1])
    probe_gain = np.array([smp(np.full(64, ri, dtype=complex))[-1] / ri
                           for ri in r])
    np.testing.assert_allclose(smp.gain_curve(r)[0], probe_gain, rtol=1e-9)


def test_branch_delays_metadata():
    smp = SplineMemoryPolynomial(n_knots=4, r_max=1.0, memory_depth=3)
    assert smp.branch_delays() == [(0, 0), (1, 1), (2, 2)]
    sgmp = SplineGMP(n_knots=4, r_max=1.0, memory_depth=2, lag_memory=1,
                     lag_span=2, lead_memory=1, lead_span=1)
    assert sgmp.branch_delays() == [(0, 0), (1, 1), (0, 1), (0, 2),
                                    (0, -1)]
    assert len(sgmp.branch_delays()) == sgmp.n_branches


def test_mp_gain_curve():
    m = MemoryPolynomialModel(order=3, memory_depth=2)
    m.coeffs = np.array([1.0, 0.5, -0.25, 0.1, 0.0, 0.05], dtype=complex)
    r = np.array([0.0, 0.5, 1.0])
    g = m.gain_curve(r)
    np.testing.assert_allclose(g[0], 1.0 + 0.5 * r - 0.25 * r**2)
    np.testing.assert_allclose(g[1], 0.1 + 0.05 * r**2)


def test_two_tone_budget_has_spline_recipe():
    from padpd.two_tone import recommend_dpd_budget
    b = recommend_dpd_budget(4.0)          # strong memory scalar input
    sc = b["spline_config"]
    assert sc["memory_depth"] == b["memory_depth"]
    assert sc["degree"] == 3 and sc["placement"] == "hybrid"
    j = sc["n_knots"] - 1 + 3
    depth = sc["memory_depth"]
    cross = (sc.get("lag_memory", 0) * sc.get("lag_span", 0)
             + sc.get("lead_memory", 0) * sc.get("lead_span", 0))
    assert b["spline_est_coeffs"] == j * depth + (j - 1) * cross
    assert b["spline_runtime_macs"] == 4 * (depth + cross)
    assert "spline" in b["rationale"]
    # cross-term case carries lag/lead kwargs for SplineGMP.from_signal
    assert ("lag_memory" in sc) == b["use_cross_terms"]


# ---- estimation upgrades (P-spline penalty / WLS) -------------------

def test_lstsq_fit_default_path_unchanged():
    """weights=None, penalty=None must reproduce the plain solver."""
    from padpd.pa.base import lstsq_fit
    rng = np.random.default_rng(5)
    phi = (rng.standard_normal((500, 12))
           + 1j * rng.standard_normal((500, 12)))
    y = rng.standard_normal(500) + 1j * rng.standard_normal(500)
    ref, *_ = np.linalg.lstsq(phi, y, rcond=None)
    np.testing.assert_array_equal(lstsq_fit(phi, y), ref)
    # relative ridge unchanged too
    a = phi.conj().T @ phi
    lam = 1e-3 * np.trace(a).real / a.shape[0]
    ref_r = np.linalg.solve(a + lam * np.eye(12), phi.conj().T @ y)
    np.testing.assert_array_equal(lstsq_fit(phi, y, 1e-3), ref_r)


def test_smoothness_penalty_reduces_roughness(pa_data):
    """P-spline penalty tames control-point curvature on a noisy fit at
    negligible NMSE cost."""
    x, y = pa_data
    rng = np.random.default_rng(6)
    y_noisy = y + 0.01 * np.sqrt(np.mean(np.abs(y) ** 2)) * (
        rng.standard_normal(len(y)) + 1j * rng.standard_normal(len(y)))
    proto = SplineMemoryPolynomial.from_signal(x, n_knots=12,
                                               memory_depth=4)

    def rough(model):
        return float(np.linalg.norm(model.smoothness_penalty()
                                    @ model.coeffs))

    plain = SplineMemoryPolynomial(knots=proto.knots,
                                   memory_depth=4).fit(x, y_noisy)
    smooth = SplineMemoryPolynomial(knots=proto.knots, memory_depth=4).fit(
        x, y_noisy, smoothness=1e-3)
    assert rough(smooth) < rough(plain)
    assert nmse_db(y, smooth(x)) < nmse_db(y, plain(x)) + 1.0


def test_wls_weights_downweight_corrupted_segment(pa_data):
    x, y = pa_data
    y_bad = y.copy()
    n = len(y)
    seg = slice(n // 4, n // 4 + n // 10)
    rng = np.random.default_rng(7)
    y_bad[seg] += 0.5 * (rng.standard_normal(y_bad[seg].size)
                         + 1j * rng.standard_normal(y_bad[seg].size))
    w = np.ones(n)
    w[seg] = 1e-6
    proto = SplineMemoryPolynomial.from_signal(x, n_knots=8, memory_depth=4)
    unweighted = SplineMemoryPolynomial(knots=proto.knots,
                                        memory_depth=4).fit(x, y_bad)
    weighted = SplineMemoryPolynomial(knots=proto.knots, memory_depth=4).fit(
        x, y_bad, weights=w)
    clean = np.ones(n, dtype=bool)
    clean[seg] = False
    e_u = nmse_db(y[clean], unweighted(x)[clean])
    e_w = nmse_db(y[clean], weighted(x)[clean])
    assert e_w < e_u - 3


# ---- widely-linear (conjugate image) branches -----------------------

def _iq_pa():
    from padpd.pa import IQImbalancePA
    return IQImbalancePA(ReferencePA(drive=0.14), gain_db=0.3,
                         phase_deg=3.0)


def test_iq_imbalance_pa_irr():
    from padpd.pa import IQImbalancePA, iq_imbalance_coeffs
    pa = _iq_pa()
    assert 28 < pa.irr_db < 33            # 0.3 dB / 3 deg -> ~30 dB IRR
    a, b = iq_imbalance_coeffs(0.0, 0.0)  # perfect modulator
    assert a == 1.0 and b == 0.0


def test_conjugate_counts_config_and_passthrough():
    m = SplineMemoryPolynomial(n_knots=6, r_max=1.0, memory_depth=3,
                               conjugate=True)
    assert m.n_branches == 6 and m.n_coeffs == 6 * m.n_basis
    assert m.branch_conjugate() == [False] * 3 + [True] * 3
    assert m.branch_delays() == [(0, 0), (1, 1), (2, 2)] * 2
    assert m.get_config()["conjugate"] is True
    rng = np.random.default_rng(8)
    x = (rng.standard_normal(2000) + 1j * rng.standard_normal(2000)) * 0.2
    m.coeffs = m.passthrough_coeffs()     # conj blocks zero -> identity
    np.testing.assert_allclose(m(x), x, atol=1e-12)


def test_conjugate_exact_recovery():
    rng = np.random.default_rng(9)
    x = (rng.standard_normal(20_000) + 1j * rng.standard_normal(20_000))
    x /= np.sqrt(2) * 2
    truth = SplineMemoryPolynomial(n_knots=5, r_max=1.5, memory_depth=2,
                                   conjugate=True)
    n = truth.n_coeffs
    truth.coeffs = (rng.standard_normal(n)
                    + 1j * rng.standard_normal(n)) * 0.1
    truth.coeffs[:truth.n_basis] += 1.0
    y = truth(x)
    fitted = SplineMemoryPolynomial(knots=truth.knots, memory_depth=2,
                                    conjugate=True).fit(x, y)
    assert nmse_db(y, fitted(x)) < -100


def test_conjugate_branch_lifts_image_floor():
    """Nested-model ablation (report's M0 -> M1/M2): on a TX-IQ-imbalanced
    PA the phase-equivariant model floors at the image level (~IRR);
    widely-linear branches recover >10 dB of both modeling NMSE and
    post-DPD EVM."""
    from padpd.dpd import ILAPredistorter
    from padpd.metrics import evm_of_signal
    pa = _iq_pa()
    wf_t = generate_ofdm(OFDMConfig(bandwidth_hz=80e6, qam_order=1024,
                                    n_symbols=8, seed=0))
    wf_v = generate_ofdm(OFDMConfig(bandwidth_hz=80e6, qam_order=1024,
                                    n_symbols=8, seed=1))
    x, xv = wf_t.x, wf_v.x
    y, yv = pa(x), pa(xv)

    plain = SplineMemoryPolynomial.from_signal(
        x, n_knots=8, memory_depth=4).fit(x, y, regularization=1e-9)
    wl = SplineMemoryPolynomial.from_signal(
        x, n_knots=8, memory_depth=4, conjugate=True
    ).fit(x, y, regularization=1e-9)
    e_plain = nmse_db(yv, plain(xv))
    e_wl = nmse_db(yv, wl(xv))
    assert -34 < e_plain < -26            # pinned near the ~30 dB IRR
    assert e_wl < e_plain - 10

    def dpd_evm(conj):
        dpd = ILAPredistorter(
            lambda: SplineMemoryPolynomial.from_signal(
                x, n_knots=8, memory_depth=4, conjugate=conj),
            n_iterations=2, fit_kwargs={"regularization": 1e-9})
        dpd.fit(pa, x)
        return evm_of_signal(pa(dpd(xv)), wf_v).db

    assert dpd_evm(True) < dpd_evm(False) - 10
