import numpy as np
import pytest

from padpd.pa import (GMPModel, MemoryPolynomialModel, ReferencePA, SalehPA,
                      nmse_db)
from padpd.waveform import OFDMConfig, generate_ofdm


@pytest.fixture(scope="module")
def ofdm_signal():
    cfg = OFDMConfig(bandwidth_hz=80e6, qam_order=256, n_symbols=8, seed=11)
    return generate_ofdm(cfg).x


@pytest.fixture(scope="module")
def pa_data(ofdm_signal):
    pa = ReferencePA()
    return ofdm_signal, pa(ofdm_signal)


def test_saleh_compression_and_gain():
    pa = SalehPA()
    r = np.linspace(0.01, 1.5, 100)
    out = np.abs(pa(r.astype(complex)))
    gain = out / r
    # gain monotonically decreases with drive level (compression)
    assert np.all(np.diff(gain) < 0)
    assert gain[0] == pytest.approx(pa.small_signal_gain, rel=1e-3)


def test_reference_pa_has_memory_and_compression(pa_data):
    x, y = pa_data
    # memoryless best fit cannot explain a memory PA well
    memoryless = MemoryPolynomialModel(order=9, memory_depth=1).fit(x, y)
    with_memory = MemoryPolynomialModel(order=9, memory_depth=4).fit(x, y)
    e0 = nmse_db(y, memoryless(x))
    e1 = nmse_db(y, with_memory(x))
    assert e1 < e0 - 3  # memory taps improve fit by >3 dB
    # compression: large-signal gain below small-signal gain
    r = np.abs(x)
    g = np.abs(y) / np.where(r > 0, r, 1)
    small = g[r < np.percentile(r, 10)].mean()
    large = g[r > np.percentile(r, 99)].mean()
    assert large < 0.9 * small


def test_mp_exact_recovery():
    """MP fit on data generated by an MP model recovers it near-exactly."""
    rng = np.random.default_rng(0)
    x = (rng.standard_normal(20_000) + 1j * rng.standard_normal(20_000))
    x /= np.sqrt(2)
    truth = MemoryPolynomialModel(order=5, memory_depth=3)
    truth.coeffs = (rng.standard_normal(15) + 1j * rng.standard_normal(15)) * 0.1
    truth.coeffs[0] = 1.0
    y = truth(x)
    fitted = MemoryPolynomialModel(order=5, memory_depth=3).fit(x, y)
    assert nmse_db(y, fitted(x)) < -100


def test_gmp_fits_reference_pa(pa_data):
    x, y = pa_data
    gmp = GMPModel().fit(x, y)
    err = nmse_db(y, gmp(x))
    assert err < -35


def test_gmp_beats_mp(pa_data):
    x, y = pa_data
    mp = MemoryPolynomialModel(order=7, memory_depth=4).fit(x, y)
    gmp = GMPModel().fit(x, y)
    assert nmse_db(y, gmp(x)) <= nmse_db(y, mp(x))


def test_gmp_generalizes(pa_data):
    """Fit on one signal, validate on an unseen one (no overfitting)."""
    x_train, y_train = pa_data
    cfg = OFDMConfig(bandwidth_hz=80e6, qam_order=256, n_symbols=8, seed=99)
    x_val = generate_ofdm(cfg).x
    y_val = ReferencePA()(x_val)
    gmp = GMPModel().fit(x_train, y_train)
    assert nmse_db(y_val, gmp(x_val)) < -35


def test_unfitted_model_raises():
    with pytest.raises(RuntimeError):
        GMPModel()(np.zeros(10, dtype=complex))


def test_gmp_constructor_validates():
    import pytest
    from padpd.pa import GMPModel
    with pytest.raises(ValueError):
        GMPModel(order=0)
    with pytest.raises(ValueError):
        GMPModel(memory_depth=0)
    with pytest.raises(ValueError):
        GMPModel(lag_span=-1)


def test_mp_n_coeffs():
    from padpd.pa import MemoryPolynomialModel
    assert MemoryPolynomialModel(order=7, memory_depth=4).n_coeffs == 28
