"""RTL generation for the fixed-point DPD coefficient datapath.

The deployment path so far exported integer coefficients and bit-true
reference vectors but stopped short of hardware. This module closes that
gap: it emits a synthesizable Verilog complex multiply-accumulate engine
that computes the DPD coefficient dot product

    y(n) = sum_k  coeff_k * phi_k(n)

(the bulk of a linear-in-params DPD, mapping to N complex DSP multipliers)
with the quantized coefficients baked in as a ROM, plus a self-checking
testbench. Everything works in integer counts so the arithmetic is
bit-exact; :func:`verify_with_iverilog` runs the testbench under Icarus
Verilog and confirms every output matches the Python integer reference.

The basis-generation block (delays, |x|^k) is left as a separate
front-end: it needs magnitude/CORDIC hardware whose generation and
verification is a project of its own. The coefficient MAC is the part
that dominates area and that this generator makes real and checkable.
"""

from __future__ import annotations

import math
import shutil
import subprocess
from pathlib import Path

import numpy as np

from .fixed_point import _pow2_step, quantize_symmetric


def _to_int(x: np.ndarray, step: float) -> np.ndarray:
    return np.round(np.asarray(x) / step).astype(np.int64)


def quantize_to_int(coeffs: np.ndarray, w_bits: int):
    """Quantized integer coefficients + their power-of-two step."""
    peak = max(np.abs(coeffs.real).max(), np.abs(coeffs.imag).max())
    step = _pow2_step(peak, w_bits)
    cq = quantize_symmetric(coeffs, w_bits)
    return _to_int(cq.real, step), _to_int(cq.imag, step), step


def _hex(v: int, width: int) -> str:
    """Two's-complement hex of a signed int at the given bit width."""
    return f"{v & ((1 << width) - 1):0{(width + 3) // 4}x}"


def generate_verilog(coeff_int_re, coeff_int_im, data_bits: int,
                     coeff_bits: int, module: str = "dpd_mac") -> str:
    """Emit the parametric complex-MAC module with coefficients baked in."""
    n = len(coeff_int_re)
    prod_bits = data_bits + coeff_bits + 1          # a*b then +/- another
    acc_bits = prod_bits + math.ceil(math.log2(2 * n)) + 1
    cr = "\n".join(f"    cr[{k}] = -sd{-int(coeff_int_re[k])};"
                   if coeff_int_re[k] < 0 else
                   f"    cr[{k}] = sd{int(coeff_int_re[k])};"
                   for k in range(n)).replace("sd", "'sd")
    ci = "\n".join(f"    ci[{k}] = -sd{-int(coeff_int_im[k])};"
                   if coeff_int_im[k] < 0 else
                   f"    ci[{k}] = sd{int(coeff_int_im[k])};"
                   for k in range(n)).replace("sd", "'sd")
    return f"""// Auto-generated by padpd.deploy.rtl -- fixed-point DPD complex MAC.
// y(n) = sum_k coeff_k * phi_k(n),  N={n} taps.
// Combinational (fully parallel); pipeline for timing closure as needed.
`timescale 1ns/1ps
module {module} #(
    parameter integer N  = {n},
    parameter integer DW = {data_bits},   // input basis sample width
    parameter integer CW = {coeff_bits},  // coefficient width
    parameter integer AW = {acc_bits}     // accumulator width
) (
    input  wire signed [N*DW-1:0] phi_re_flat,
    input  wire signed [N*DW-1:0] phi_im_flat,
    output reg  signed [AW-1:0]   y_re,
    output reg  signed [AW-1:0]   y_im
);
    reg signed [CW-1:0] cr [0:N-1];
    reg signed [CW-1:0] ci [0:N-1];
    integer k;
    reg signed [DW-1:0] pr, pi;
    initial begin
{cr}
{ci}
    end
    always @* begin
        y_re = 0;
        y_im = 0;
        for (k = 0; k < N; k = k + 1) begin
            pr = phi_re_flat[k*DW +: DW];
            pi = phi_im_flat[k*DW +: DW];
            // (cr+j*ci)*(pr+j*pi)
            y_re = y_re + cr[k]*pr - ci[k]*pi;
            y_im = y_im + cr[k]*pi + ci[k]*pr;
        end
    end
endmodule
"""


def generate_testbench(n: int, data_bits: int, acc_bits: int,
                       n_vectors: int, module: str = "dpd_mac") -> str:
    return f"""`timescale 1ns/1ps
module tb;
    localparam integer N  = {n};
    localparam integer DW = {data_bits};
    localparam integer AW = {acc_bits};
    localparam integer NV = {n_vectors};
    reg  signed [N*DW-1:0] phi_re_flat, phi_im_flat;
    wire signed [AW-1:0]   y_re, y_im;
    {module} dut(.phi_re_flat(phi_re_flat), .phi_im_flat(phi_im_flat),
                 .y_re(y_re), .y_im(y_im));
    reg signed [DW-1:0] vin_re [0:NV*N-1];
    reg signed [DW-1:0] vin_im [0:NV*N-1];
    reg signed [AW-1:0] exp_re [0:NV-1];
    reg signed [AW-1:0] exp_im [0:NV-1];
    integer v, k, errors;
    initial begin
        $readmemh("phi_re.mem", vin_re);
        $readmemh("phi_im.mem", vin_im);
        $readmemh("exp_re.mem", exp_re);
        $readmemh("exp_im.mem", exp_im);
        errors = 0;
        for (v = 0; v < NV; v = v + 1) begin
            for (k = 0; k < N; k = k + 1) begin
                phi_re_flat[k*DW +: DW] = vin_re[v*N + k];
                phi_im_flat[k*DW +: DW] = vin_im[v*N + k];
            end
            #1;
            if (y_re !== exp_re[v] || y_im !== exp_im[v]) begin
                errors = errors + 1;
                $display("MISMATCH v=%0d got(%0d,%0d) exp(%0d,%0d)",
                         v, y_re, y_im, exp_re[v], exp_im[v]);
            end
        end
        $display("RESULT errors=%0d of %0d", errors, NV);
        $finish;
    end
endmodule
"""


def emit_rtl(model, out_dir: str, w_bits: int = 12, data_bits: int = 12,
             n_vectors: int = 64, seed: int = 0) -> dict:
    """Generate Verilog + testbench + bit-true reference vectors.

    ``model`` is a fitted linear-params model (GMP/DDR/MP). Returns the
    written paths and the module's tap/width parameters.
    """
    if getattr(model, "coeffs", None) is None:
        raise ValueError("model must be fitted")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    cr_i, ci_i, step_w = quantize_to_int(model.coeffs, w_bits)
    n = len(cr_i)

    # random but reproducible basis vectors, quantized to integer counts
    rng = np.random.default_rng(seed)
    phi = (rng.standard_normal((n_vectors, n))
           + 1j * rng.standard_normal((n_vectors, n)))
    peak = max(np.abs(phi.real).max(), np.abs(phi.imag).max())
    step_p = _pow2_step(peak, data_bits)
    pr = _to_int(quantize_symmetric(phi.real, data_bits), step_p)
    pi = _to_int(quantize_symmetric(phi.imag, data_bits), step_p)

    # integer reference MAC (arbitrary precision, the golden output)
    exp_re = (pr @ cr_i) - (pi @ ci_i)
    exp_im = (pr @ ci_i) + (pi @ cr_i)

    prod_bits = data_bits + w_bits + 1
    acc_bits = prod_bits + math.ceil(math.log2(2 * n)) + 1

    (out / f"dpd_mac.v").write_text(
        generate_verilog(cr_i, ci_i, data_bits, w_bits))
    (out / "tb.v").write_text(
        generate_testbench(n, data_bits, acc_bits, n_vectors))
    (out / "phi_re.mem").write_text(
        "\n".join(_hex(int(v), data_bits) for v in pr.ravel()) + "\n")
    (out / "phi_im.mem").write_text(
        "\n".join(_hex(int(v), data_bits) for v in pi.ravel()) + "\n")
    (out / "exp_re.mem").write_text(
        "\n".join(_hex(int(v), acc_bits) for v in exp_re) + "\n")
    (out / "exp_im.mem").write_text(
        "\n".join(_hex(int(v), acc_bits) for v in exp_im) + "\n")

    return {"dir": str(out), "verilog": str(out / "dpd_mac.v"),
            "testbench": str(out / "tb.v"), "n_taps": n,
            "data_bits": data_bits, "coeff_bits": w_bits,
            "acc_bits": acc_bits, "n_vectors": n_vectors,
            "coeff_step": step_w, "data_step": step_p}


def verify_with_iverilog(out_dir: str) -> dict:
    """Compile+run the testbench under Icarus Verilog; parse pass/fail.

    Returns ``{"available", "passed", "errors", "n_vectors", "output"}``.
    ``available`` is False (and the rest None) if iverilog is not on PATH.
    """
    if shutil.which("iverilog") is None or shutil.which("vvp") is None:
        return {"available": False, "passed": None, "errors": None,
                "n_vectors": None, "output": "iverilog not installed"}
    out = Path(out_dir)
    vvp = out / "sim.vvp"
    comp = subprocess.run(
        ["iverilog", "-g2012", "-o", str(vvp), str(out / "dpd_mac.v"),
         str(out / "tb.v")], capture_output=True, text=True)
    if comp.returncode != 0:
        return {"available": True, "passed": False, "errors": None,
                "n_vectors": None, "output": comp.stderr.strip()}
    run = subprocess.run(["vvp", str(vvp)], cwd=str(out),
                         capture_output=True, text=True)
    text = run.stdout.strip()
    errors = n_vec = None
    for line in text.splitlines():
        if line.startswith("RESULT"):
            parts = line.replace("errors=", "").replace("of", "").split()
            errors, n_vec = int(parts[1]), int(parts[2])
    return {"available": True, "passed": errors == 0 and errors is not None,
            "errors": errors, "n_vectors": n_vec, "output": text}
