package com.padpd.chart

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Parses specs that Python actually produced.
 *
 * `gallery_specs.json` is generated by `padpd_mobile.gallery` through
 * `api.gallery_chart` and committed as a fixture, so this is a genuine
 * cross-language contract test rather than a check against a hand-written
 * sample that would drift with whatever this file expects. A renamed key
 * on either side fails here instead of drawing an empty chart on a phone.
 *
 * Regenerate with the snippet in android/README.md when the schema
 * changes on purpose.
 */
class ChartSpecParseTest {

    private val specs: Map<String, ChartSpec> by lazy {
        val text = javaClass.classLoader!!
            .getResourceAsStream("gallery_specs.json")!!
            .bufferedReader().readText()
        val raw = ChartJson.parseToJsonElement(text)
        (raw as kotlinx.serialization.json.JsonObject).mapValues { (_, v) ->
            ChartJson.decodeFromJsonElement(ChartSpec.serializer(), v)
        }
    }

    @Test
    fun everyGalleryChartParses() {
        assertEquals(14, specs.size)
        for ((id, spec) in specs) {
            assertTrue("$id has no panels", spec.panels.isNotEmpty())
            for (p in spec.panels) {
                assertTrue("$id: unknown kind ${p.kind}",
                           p.kind in setOf("line", "scatter", "bar"))
                assertTrue("$id: no series", p.series.isNotEmpty())
                for (s in p.series) {
                    assertTrue("$id: empty blob key", s.x.isNotEmpty() && s.y.isNotEmpty())
                    assertTrue("$id: bad axis ${s.axis}",
                               s.axis == "left" || s.axis == "right")
                }
            }
        }
    }

    @Test
    fun twinAxisSurvives() {
        val p = specs.getValue("three_loop").panels[0]
        assertNotNull(p.y2label)
        assertTrue(p.hasRightAxis)
        assertEquals(listOf("left", "left", "left", "right"), p.series.map { it.axis })
    }

    @Test
    fun logScalesSurvive() {
        assertEquals("log", specs.getValue("ccdf").panels[0].yscale)
        assertEquals("log", specs.getValue("two_tone").panels[0].xscale)
    }

    @Test
    fun categoricalTicksSurvive() {
        val ticks = specs.getValue("bitwidth").panels[0].xTicks
        assertNotNull(ticks)
        assertEquals(listOf("W16", "W12", "W10", "W8"), ticks!!.map { it.label })
    }

    @Test
    fun equalAspectAndMultiPanelSurvive() {
        assertTrue(specs.getValue("constellation").panels[0].aspectEqual)
        assertEquals(2, specs.getValue("amam").panels.size)
    }

    @Test
    fun overlaysSurvive() {
        val codesign = specs.getValue("codesign").panels[0]
        assertTrue(codesign.vspans.isNotEmpty())
        assertTrue(codesign.hlines.isNotEmpty())
        assertEquals("right", codesign.hlines[0].axis)
    }

    @Test
    fun barPanelCarriesItsGroupWidth() {
        val bars = specs.getValue("bars").panels[0]
        assertEquals("bar", bars.kind)
        assertTrue("grouped width should be 0.8/k", bars.barWidth in 0.05..0.8)
        assertEquals(4, bars.xTicks!!.size)
    }

    @Test
    fun ylimIsCarriedForPsdButAbsentElsewhere() {
        // figs.py fixes the PSD axis at -90..5 dBr; nothing else pins one.
        assertEquals(listOf(-90.0, 5.0), specs.getValue("psd").panels[0].ylim)
        assertNull(specs.getValue("time").panels[0].ylim)
    }

    @Test
    fun unknownKeysDoNotBreakParsing() {
        // The Python side may add a field before the renderer reads it.
        val spec = ChartJson.decodeFromString(
            ChartSpec.serializer(),
            """{"panels":[{"kind":"line","series":[
               {"label":"a","x":"b0","y":"b1","future_field":7}],
               "brand_new_key":true}]}""",
        )
        assertEquals(1, spec.panels[0].series.size)
    }
}
