"""Generate the app icon assets from the source artwork.

Takes ``packaging/icon/source.png`` (a square tile) and emits:

- ``packaging/icon/padpd.ico`` — multi-resolution Windows icon (16..256),
  used by the PyInstaller EXE (see ``padpd_qt.spec``);
- ``gui_qt/assets/padpd.png`` — a 512px RGBA icon bundled with the app and
  set as the window / taskbar icon (see ``gui_qt/main.py``);
- ``android/app/src/main/res/mipmap-*`` — the launcher icon, so the phone
  shows the same artwork as the desktop rather than the stock Android
  robot. Legacy PNGs for API 24-25 and an adaptive icon for 26+.

The outer square corners are rounded to transparency so the tile reads as
a proper app icon instead of a black square. Re-run after replacing
``source.png``:  ``python packaging/make_icon.py``
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SRC = HERE / "icon" / "source.png"
ICO = HERE / "icon" / "padpd.ico"
PNG = ROOT / "gui_qt" / "assets" / "padpd.png"

ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]
CORNER_FRAC = 0.16          # rounded-corner radius as a fraction of size

ANDROID_RES = ROOT / "android" / "app" / "src" / "main" / "res"

# Launcher icon edge in px per density bucket. 48dp is the legacy icon;
# an adaptive icon's layers are 108dp, of which the system mask keeps
# only the middle 72dp - the outer ring is bleed for parallax.
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
LEGACY_DP = 48
ADAPTIVE_DP = 108


def circular(img: Image.Image, size: int) -> Image.Image:
    """Square-resize to ``size`` and clip to a circle."""
    im = img.convert("RGBA").resize((size, size), Image.LANCZOS)
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).ellipse([0, 0, size - 1, size - 1], fill=255)
    im.putalpha(mask)
    return im


def android(src: Image.Image) -> None:
    """Emit the launcher icon in every form Android asks for.

    The artwork is a full-bleed tile - its content reaches all four edges
    - so the adaptive icon puts it in the *background* layer at full
    bleed and leaves the foreground transparent, letting the launcher's
    own mask crop it to whatever shape the device uses. Scaling the tile
    down into the 72dp safe zone instead would render it as a small
    square badge floating on a flat field, which is not what the desktop
    shows.

    The legacy PNGs keep the rounded-rect treatment the desktop icon
    uses, because on API 24-25 nothing masks them.
    """
    for bucket, scale in DENSITIES.items():
        out = ANDROID_RES / f"mipmap-{bucket}"
        out.mkdir(parents=True, exist_ok=True)
        legacy = int(LEGACY_DP * scale)
        rounded(src, legacy).save(out / "ic_launcher.png")
        circular(src, legacy).save(out / "ic_launcher_round.png")
        # Full bleed, unrounded: the adaptive mask does the shaping.
        adaptive = int(ADAPTIVE_DP * scale)
        (src.convert("RGBA").resize((adaptive, adaptive), Image.LANCZOS)
            .save(out / "ic_launcher_background.png"))

    anydpi = ANDROID_RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    xml = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packaging/make_icon.py. Do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <!-- The artwork is a full-bleed tile and lives in the background
         layer; there is no separate mark to float above it. -->
    <foreground android:drawable="@android:color/transparent" />
</adaptive-icon>
"""
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (anydpi / name).write_text(xml, encoding="utf-8")
    print(f"wrote {ANDROID_RES}/mipmap-* "
          f"({len(DENSITIES)} densities + anydpi-v26)")


def rounded(img: Image.Image, size: int) -> Image.Image:
    """Square-resize to ``size`` and clip to a rounded-rect alpha mask."""
    im = img.convert("RGBA").resize((size, size), Image.LANCZOS)
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, size - 1, size - 1], radius=int(size * CORNER_FRAC), fill=255)
    im.putalpha(mask)
    return im


def main() -> None:
    if not SRC.exists():
        raise SystemExit(f"missing {SRC} — drop the source artwork there")
    src = Image.open(SRC)
    if src.width != src.height:                       # center-crop to square
        s = min(src.size)
        left, top = (src.width - s) // 2, (src.height - s) // 2
        src = src.crop((left, top, left + s, top + s))

    PNG.parent.mkdir(parents=True, exist_ok=True)
    rounded(src, 512).save(PNG)
    print(f"wrote {PNG}")

    base = rounded(src, 256)
    base.save(ICO, sizes=[(s, s) for s in ICO_SIZES])
    print(f"wrote {ICO} ({', '.join(str(s) for s in ICO_SIZES)})")

    android(src)


if __name__ == "__main__":
    main()
